In [1]:
import numpy as np
import pandas as pd
import pandas_profiling

import plotly 
plotly.tools.set_credentials_file(username='randyjulian', api_key='ZnlKxIsarJcpbs1roIO4')
import plotly.plotly as py
import plotly.graph_objs as go


pd.set_option('display.max_columns', 200)

In [2]:
commitments=pd.read_csv("../data/hack4climate_commitments_070319.csv")
subnationals=pd.read_csv("../data/hack4climate_contextuals_090319.csv")
future_industry=pd.read_excel("../data/CW_NDC_Content_WB_07032018.xlsx",header=3)
current_industry=pd.read_excel("../data/CW_CAIT_GHG_Emissions_31102017.xlsx",1,header=1)
SDG_linkages=pd.read_excel("../data/CW_WRI_NDC_SDGs_Linkages_31102017.xlsx",0,header=3)

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning:

Columns (11,17,20,21,35) have mixed types. Specify dtype option on import or set low_memory=False.

## Sector Classification

### INDC Contributions based on SDG

In [3]:
SDG_linkages['Sector_list']=SDG_linkages.Sector.apply(lambda x: x.split(", "))

In [4]:
slist = [st for row in SDG_linkages.Sector.apply(lambda x: x.split(", ")) for st in row]

In [5]:
SDG_linkages["Energy_count"]=SDG_linkages.apply(lambda x: 1 if 'Energy Efficiency' in x.Sector_list or 'Renewable Energy' in x.Sector_list else 0,axis=1)
SDG_linkages["Industrial_count"]=SDG_linkages.apply(lambda x: 1 if 'Industry ' in x.Sector_list else 0,axis=1)
SDG_linkages["Agriculture_count"]=SDG_linkages.apply(lambda x: 1 if 'Agriculture' in x.Sector_list or 'Agriculture  ' in x.Sector_list or 'Agriculture  and land use ' in x.Sector_list else 0,axis=1)
SDG_linkages["Waste_count"]=SDG_linkages.apply(lambda x: 1 if 'Waste' in x.Sector_list else 0,axis=1)
SDG_linkages["LandForestry_count"]=SDG_linkages.apply(lambda x: 1 if 'Forest and land use ' in x.Sector_list or 'Forest ' in x.Sector_list else 0,axis=1)
SDG_linkages["ManufacturingConstruction_count"]=SDG_linkages.apply(lambda x: 1 if 'Rural Development' in x.Sector_list or 'Cities and Urban Development' in x.Sector_list or 'Infrastructure' in x.Sector_list else 0,axis=1)
SDG_linkages["Transportation_count"]=SDG_linkages.apply(lambda x: 1 if 'Transport' in x.Sector_list else 0,axis=1)
SDG_linkages["Other_count"]=SDG_linkages.apply(lambda x: 1 if 'cross-cutting' in x.Sector_list or 
                                               'Water' in x.Sector_list or 'Health ' in x.Sector_list or
                                               'health ' in x.Sector_list or 'Sanitation ' in x.Sector_list or
                                               'Education ' in x.Sector_list or 'Oceans and Fisheries' in x.Sector_list or
                                               'education' in x.Sector_list or 'water' in x.Sector_list or 'Not specified' in x.Sector_list
                                               else 0,axis=1)

In [6]:
SDG_linkages["Other_count_overlap"]=SDG_linkages.apply(lambda x: 0 if x.Energy_count==1 or x.Industrial_count==1 or
                                                        x.Agriculture_count==1 or x.Waste_count==1 or
                                                        x.LandForestry_count==1 or x.ManufacturingConstruction_count==1 or 
                                                        x.Transportation_count==1 else 1,axis=1)

In [7]:
SDG_linkages_graph_data=SDG_linkages.groupby("Country").sum()
SDG_linkages_graph_data['total']=SDG_linkages_graph_data.iloc[:,[0,1,2,3,4,5,6,8]].apply(sum, axis=1)

In [8]:
for col in [col for col in SDG_linkages_graph_data.columns if "_count" in col]:
    SDG_linkages_graph_data[col+"_percent"] = SDG_linkages_graph_data[col]*100 / SDG_linkages_graph_data.total

In [9]:
#SDG_linkages_graph_data.drop('Other_count_percent',inplace=True, axis=1)
SDG_linkages_graph_data

,Energy_count,Industrial_count,Agriculture_count,Waste_count,LandForestry_count,ManufacturingConstruction_count,Transportation_count,Other_count,Other_count_overlap,total,Energy_count_percent,Industrial_count_percent,Agriculture_count_percent,Waste_count_percent,LandForestry_count_percent,ManufacturingConstruction_count_percent,Transportation_count_percent,Other_count_percent,Other_count_overlap_percent
Country,,,,,,,,,,,,,,,,,,,
Federal Democratic Republic of Ethiopia,8,3,16,0,15,13,6,48,45,106,7.547170,2.830189,15.094340,0.000000,14.150943,12.264151,5.660377,45.283019,42.452830
Afghanistan,8,0,10,1,7,0,0,28,24,50,16.000000,0.000000,20.000000,2.000000,14.000000,0.000000,0.000000,56.000000,48.000000
Albania,1,1,0,0,0,0,0,0,0,2,50.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Algeria,11,0,6,6,6,7,8,19,15,59,18.644068,0.000000,10.169492,10.169492,10.169492,11.864407,13.559322,32.203390,25.423729
Angola,10,0,16,0,18,4,0,20,24,72,13.888889,0.000000,22.222222,0.000000,25.000000,5.555556,0.000000,27.777778,33.333333
Antigua and Barbuda,11,0,4,3,2,6,1,29,24,51,21.568627,0.000000,7.843137,5.882353,3.921569,11.764706,1.960784,56.862745,47.058824
Argentina,0,1,1,0,1,1,0,18,18,22,0.000000,4.545455,4.545455,0.000000,4.545455,4.545455,0.000000,81.818182,81.818182
Armenia,0,0,0,0,4,1,0,20,20,25,0.000000,0.000000,0.000000,0.000000,16.000000,4.000000,0.000000,80.000000,80.000000
Australia,6,2,0,0,0,0,3,9,9,20,30.000000,10.000000,0.000000,0.000000,0.000000,0.000000,15.000000,45.000000,45.000000
Azerbaijan,21,0,2,2,3,6,8,5,4,46,45.652174,0.000000,4.347826,4.347826,6.521739,13.043478,17.391304,10.869565,8.695652
Bahamas,7,3,5,0,6,2,2,10,13,38,18.421053,7.894737,13.157895,0.000000,15.789474,5.263158,5.263158,26.315789,34.210526
Bahrain,18,3,0,1,1,1,4,7,8,36,50.000000,8.333333,0.000000,2.777778,2.777778,2.777778,11.111111,19.444444,22.222222
Bangladesh,32,9,9,4,18,13,4,31,27,116,27.586207,7.758621,7.758621,3.448276,15.517241,11.206897,3.448276,26.724138,23.275862
Barbados,15,1,2,3,2,0,2,26,27,52,28.846154,1.923077,3.846154,5.769231,3.846154,0.000000,3.846154,50.000000,51.923077
Belarus,0,0,0,0,6,2,2,9,7,17,0.000000,0.000000,0.000000,0.000000,35.294118,11.764706,11.764706,52.941176,41.176471
Belize,24,2,9,10,38,9,3,52,49,144,16.666667,1.388889,6.250000,6.944444,26.388889,6.250000,2.083333,36.111111,34.027778
Benin,20,0,14,10,36,7,5,42,43,135,14.814815,0.000000,10.370370,7.407407,26.666667,5.185185,3.703704,31.111111,31.851852
Bhutan,9,8,18,2,9,8,8,19,18,80,11.250000,10.000000,22.500000,2.500000,11.250000,10.000000,10.000000,23.750000,22.500000
Bolivia,11,0,2,1,38,9,0,39,38,99,11.111111,0.000000,2.020202,1.010101,38.383838,9.090909,0.000000,39.393939,38.383838
Bosnia-Herzegovina,16,0,0,2,0,5,0,1,1,24,66.666667,0.000000,0.000000,8.333333,0.000000,20.833333,0.000000,4.166667,4.166667
Botswana,0,0,4,0,0,2,0,15,13,19,0.000000,0.000000,21.052632,0.000000,0.000000,10.526316,0.000000,78.947368,68.421053
Brazil,6,2,1,0,5,1,1,2,2,18,33.333333,11.111111,5.555556,0.000000,27.777778,5.555556,5.555556,11.111111,11.111111
Brunei,20,1,3,1,14,9,10,16,9,67,29.850746,1.492537,4.477612,1.492537,20.895522,13.432836,14.925373,23.880597,13.432836
Burkina Faso,47,5,21,3,22,11,0,27,27,136,34.558824,3.676471,15.441176,2.205882,16.176471,8.088235,0.000000,19.852941,19.852941
Burundi,3,1,25,0,11,2,0,24,19,61,4.918033,1.639344,40.983607,0.000000,18.032787,3.278689,0.000000,39.344262,31.147541
Cabo Verde,25,0,10,13,8,7,3,21,19,85,29.411765,0.000000,11.764706,15.294118,9.411765,8.235294,3.529412,24.705882,22.352941
Cambodia,21,8,12,1,14,14,5,48,41,116,18.103448,6.896552,10.344828,0.862069,12.068966,12.068966,4.310345,41.379310,35.344828
Cameroon,18,7,29,10,17,12,4,38,38,135,13.333333,5.185185,21.481481,7.407407,12.592593,8.888889,2.962963,28.148148,28.148148
Canada,4,0,0,2,0,2,8,2,2,18,22.222222,0.000000,0.000000,11.111111,0.000000,11.111111,44.444444,11.111111,11.111111
Central African Republic,10,0,35,10,39,5,0,31,29,128,7.812500,0.000000,27.343750,7.812500,30.468750,3.906250,0.000000,24.218750,22.656250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Somalia,23,2,22,1,36,33,0,95,94,211,10.900474,0.947867,10.426540,0.473934,17.061611,15.639810,0.000000,45.023697,44.549763
South Africa,5,0,0,0,5,2,5,18,12,29,17.241379,0.000000,0.000000,0.000000,17.241379,6.896552,17.241379,62.068966,41.379310
South Sudan,12,0,5,2,14,7,7,50,46,93,12.903226,0.000000,5.376344,2.150538,15.053763,7.526882,7.526882,53.763441,49.462366
Sri Lanka,21,9,35,14,20,16,29,77,67,211,9.952607,4.265403,16.587678,6.635071,9.478673,7.582938,13.744076,36.492891,31.753555
Sudan,28,0,14,10,16,8,0,45,46,122,22.950820,0.000000,11.475410,8.196721,13.114754,6.557377,0.000000,36.885246,37.704918
Suriname,16,6,5,3,15,14,0,16,16,75,21.333333,8.000000,6.666667,4.000000,20.000000,18.666667,0.000000,21.333333,21.333333
Swaziland,14,0,10,2,12,2,2,19,11,53,26.415094,0.000000,18.867925,3.773585,22.641509,3.773585,3.773585,35.849057,20.754717
Switzerland,0,0,0,0,2,0,0,1,1,3,0.000000,0.000000,0.000000,0.000000,66.666667,0.000000,0.000000,33.333333,33.333333
Tajikistan,5,2,4,0,8,1,3,19,18,41,12.195122,4.878049,9.756098,0.000000,19.512195,2.439024,7.317073,46.341463,43.902439
Thailand,4,3,3,2,2,2,5,21,21,42,9.523810,7.142857,7.142857,4.761905,4.761905,4.761905,11.904762,50.000000,50.000000
The former Yugoslav Republic of Macedonia,38,2,5,4,8,17,5,23,13,92,41.304348,2.173913,5.434783,4.347826,8.695652,18.478261,5.434783,25.000000,14.130435
Timor-Leste (East Timor),20,6,10,10,33,20,9,37,28,136,14.705882,4.411765,7.352941,7.352941,24.264706,14.705882,6.617647,27.205882,20.588235
Togo,12,0,14,7,7,18,2,23,25,85,14.117647,0.000000,16.470588,8.235294,8.235294,21.176471,2.352941,27.058824,29.411765
Tonga,35,0,7,0,8,4,9,20,16,79,44.303797,0.000000,8.860759,0.000000,10.126582,5.063291,11.392405,25.316456,20.253165
Trinidad and Tobago,4,1,0,0,0,0,1,2,2,8,50.000000,12.500000,0.000000,0.000000,0.000000,0.000000,12.500000,25.000000,25.000000
Tunisia,9,7,13,9,12,8,5,15,17,80,11.250000,8.750000,16.250000,11.250000,15.000000,10.000000,6.250000,18.750000,21.250000
Turkey,18,1,5,9,4,8,14,0,0,59,30.508475,1.694915,8.474576,15.254237,6.779661,13.559322,23.728814,0.000000,0.000000
Turkmenistan,2,1,0,0,0,0,0,6,5,8,25.000000,12.500000,0.000000,0.000000,0.000000,0.000000,0.000000,75.000000,62.500000
Tuvalu,20,0,0,0,0,2,0,5,1,23,86.956522,0.000000,0.000000,0.000000,0.000000,8.695652,0.000000,21.739130,4.347826
Uganda,5,0,11,0,13,8,0,31,16,53,9.433962,0.000000,20.754717,0.000000,24.528302,15.094340,0.000000,58.490566,30.188679
United Arab Emirates,14,3,5,5,3,2,8,15,13,53,26.415094,5.660377,9.433962,9.433962,5.660377,3.773585,15.094340,28.301887,24.528302
United Republic of Tanzania?,7,0,14,9,10,10,2,20,18,70,10.000000,0.000000,20.000000,12.857143,14.285714,14.285714,2.857143,28.571429,25.714286
United States of America,3,1,0,1,1,0,2,3,1,9,33.333333,11.111111,0.000000,11.111111,11.111111,0.000000,22.222222,33.333333,11.111111
Uruguay,6,3,12,8,8,4,8,11,8,57,10.526316,5.263158,21.052632,14.035088,14.035088,7.017544,14.035088,19.298246,14.035088
Vanuatu,10,0,1,0,6,2,0,37,37,56,17.857143,0.000000,1.785714,0.000000,10.714286,3.571429,0.000000,66.071429,66.071429
Venezuela,16,3,7,7,7,7,5,34,30,82,19.512195,3.658537,8.536585,8.536585,8.536585,8.536585,6.097561,41.463415,36.585366
Viet Nam,19,2,16,7,31,40,6,71,49,170,11.176471,1.176471,9.411765,4.117647,18.235294,23.529412,3.529412,41.764706,28.823529
Yemen,31,1,9,3,11,14,1,14,18,88,35.227273,1.136364,10.227273,3.409091,12.500000,15.909091,1.136364,15.909091,20.454545
Zambia,13,2,38,3,41,49,0,107,91,237,5.485232,0.843882,16.033755,1.265823,17.299578,20.675105,0.000000,45.147679,38.396624
Zimbabwe,6,0,10,0,4,0,0,27,26,46,13.043478,0.000000,21.739130,0.000000,8.695652,0.000000,0.000000,58.695652,56.521739

In [11]:

trace1 = go.Bar(
    x=SDG_linkages_graph_data.index,
    y=SDG_linkages_graph_data["Energy_count_percent"],
    name='Energy'
)
trace2 = go.Bar(
    x=SDG_linkages_graph_data.index,
    y=SDG_linkages_graph_data["Industrial_count_percent"],
    name='Industrial Process'
)

trace3 = go.Bar(
    x=SDG_linkages_graph_data.index,
    y=SDG_linkages_graph_data["Agriculture_count_percent"],
    name='Agriculture'
)

trace4 = go.Bar(
    x=SDG_linkages_graph_data.index,
    y=SDG_linkages_graph_data["Waste_count_percent"],
    name='Waste'
)

trace5 = go.Bar(
    x=SDG_linkages_graph_data.index,
    y=SDG_linkages_graph_data["LandForestry_count_percent"],
    name='Land Use and Forestry'
)

trace7 = go.Bar(
    x=SDG_linkages_graph_data.index,
    y=SDG_linkages_graph_data["ManufacturingConstruction_count_percent"],
    name='Manufacturing/Construction'
)

trace8 = go.Bar(
    x=SDG_linkages_graph_data.index,
    y=SDG_linkages_graph_data["Transportation_count_percent"],
    name='Transportation'
)
trace9 = go.Bar(
    x=SDG_linkages_graph_data.index,
    y=SDG_linkages_graph_data["Other_count_overlap_percent"],
    name='Others'
)
data = [trace5, trace2, trace3, trace4 ,trace1, trace7, trace8, trace9]
layout = go.Layout(
    barmode='stack',
    title='Intended Nationally Determined Contributions (INDC) by Country',
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='INDC-country')

### Current Contributions

In [12]:
current_industry_filtered=current_industry[current_industry.Year==2014].iloc[:,[0,1,11,12,13,14,15,16,17,18,19,20,21]]
current_industry_filtered=current_industry_filtered.fillna(0)
current_industry_filtered['Energy_deducted']=current_industry_filtered['Energy (MtCO2e)']-current_industry_filtered['Manufacturing/Construction (MtCO2)']-current_industry_filtered['Transportation (MtCO2)']

In [13]:
current_industry_filtered_pos=current_industry_filtered[current_industry_filtered["Land-Use Change and Forestry (MtCO2)"]>=0]
current_industry_filtered_neg=current_industry_filtered[current_industry_filtered["Land-Use Change and Forestry (MtCO2)"]<0]
current_industry_filtered_neg["Land-Use Change and Forestry (MtCO2)"]=abs(current_industry_filtered_neg["Land-Use Change and Forestry (MtCO2)"])

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [14]:
current_industry_filtered_pos["Sectoral_Sum"]=current_industry_filtered_pos.iloc[:,2:8].apply(sum, axis=1)
current_industry_filtered_neg["Sectoral_Sum"]=current_industry_filtered_neg.iloc[:,2:8].apply(sum, axis=1)

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [15]:
current_industry_filtered_pos["Energy_%"]=current_industry_filtered_pos["Energy_deducted"]*100/current_industry_filtered_pos.Sectoral_Sum
current_industry_filtered_pos["Industrial_%"]=current_industry_filtered_pos["Industrial Processes (MtCO2e)"]*100/current_industry_filtered_pos.Sectoral_Sum
current_industry_filtered_pos["Agriculture_%"]=current_industry_filtered_pos["Agriculture (MtCO2e)"]*100/current_industry_filtered_pos.Sectoral_Sum
current_industry_filtered_pos["Waste_%"]=current_industry_filtered_pos["Waste (MtCO2e)"]*100/current_industry_filtered_pos.Sectoral_Sum
current_industry_filtered_pos["LandUseandForestry_%"]=current_industry_filtered_pos["Land-Use Change and Forestry (MtCO2)"]*100/current_industry_filtered_pos.Sectoral_Sum
current_industry_filtered_pos["BunkerFuels_%"]=current_industry_filtered_pos["Bunker Fuels (MtCO2)"]*100/current_industry_filtered_pos.Sectoral_Sum
current_industry_filtered_pos["ManufacturingConstruction_%"]=current_industry_filtered_pos["Manufacturing/Construction (MtCO2)"]*100/current_industry_filtered_pos.Sectoral_Sum
current_industry_filtered_pos["Transportation_%"]=current_industry_filtered_pos["Transportation (MtCO2)"]*100/current_industry_filtered_pos.Sectoral_Sum

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:

trace1 = go.Bar(
    x=current_industry_filtered_pos.Country,
    y=current_industry_filtered_pos["Energy_%"],
    name='Energy'
)
trace2 = go.Bar(
    x=current_industry_filtered_pos.Country,
    y=current_industry_filtered_pos["Industrial_%"],
    name='Industrial Process'
)

trace3 = go.Bar(
    x=current_industry_filtered_pos.Country,
    y=current_industry_filtered_pos["Agriculture_%"],
    name='Agriculture'
)

trace4 = go.Bar(
    x=current_industry_filtered_pos.Country,
    y=current_industry_filtered_pos["Waste_%"],
    name='Waste'
)

trace5 = go.Bar(
    x=current_industry_filtered_pos.Country,
    y=current_industry_filtered_pos["LandUseandForestry_%"],
    name='Land Use and Forestry'
)

trace6 = go.Bar(
    x=current_industry_filtered_pos.Country,
    y=current_industry_filtered_pos["BunkerFuels_%"],
    name='Bunker Fuels'
)

trace7 = go.Bar(
    x=current_industry_filtered_pos.Country,
    y=current_industry_filtered_pos["ManufacturingConstruction_%"],
    name='Manufacturing/Construction'
)

trace8 = go.Bar(
    x=current_industry_filtered_pos.Country,
    y=current_industry_filtered_pos["Transportation_%"],
    name='Transportation'
)

data = [trace5, trace2, trace3, trace4 ,trace1, trace6, trace7, trace8]
layout = go.Layout(
    barmode='stack',
    title="Percentage of Green House Gas Contribution by Country (Positive Forestry Emission)"
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='GHG-pos')

In [17]:
current_industry_filtered_neg["Energy_%"]=current_industry_filtered_neg["Energy_deducted"]*100/current_industry_filtered_neg.Sectoral_Sum
current_industry_filtered_neg["Industrial_%"]=current_industry_filtered_neg["Industrial Processes (MtCO2e)"]*100/current_industry_filtered_neg.Sectoral_Sum
current_industry_filtered_neg["Agriculture_%"]=current_industry_filtered_neg["Agriculture (MtCO2e)"]*100/current_industry_filtered_neg.Sectoral_Sum
current_industry_filtered_neg["Waste_%"]=current_industry_filtered_neg["Waste (MtCO2e)"]*100/current_industry_filtered_neg.Sectoral_Sum
current_industry_filtered_neg["LandUseandForestry_%"]=abs(current_industry_filtered_neg["Land-Use Change and Forestry (MtCO2)"])*100/current_industry_filtered_neg.Sectoral_Sum
current_industry_filtered_neg["BunkerFuels_%"]=current_industry_filtered_neg["Bunker Fuels (MtCO2)"]*100/current_industry_filtered_neg.Sectoral_Sum
current_industry_filtered_neg["ManufacturingConstruction_%"]=current_industry_filtered_neg["Manufacturing/Construction (MtCO2)"]*100/current_industry_filtered_neg.Sectoral_Sum
current_industry_filtered_neg["Transportation_%"]=current_industry_filtered_neg["Transportation (MtCO2)"]*100/current_industry_filtered_neg.Sectoral_Sum

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [18]:

trace1 = go.Bar(
    x=current_industry_filtered_neg.Country,
    y=current_industry_filtered_neg["Energy_%"],
    name='Energy'
)
trace2 = go.Bar(
    x=current_industry_filtered_neg.Country,
    y=current_industry_filtered_neg["Industrial_%"],
    name='Industrial Process'
)

trace3 = go.Bar(
    x=current_industry_filtered_neg.Country,
    y=current_industry_filtered_neg["Agriculture_%"],
    name='Agriculture'
)

trace4 = go.Bar(
    x=current_industry_filtered_neg.Country,
    y=current_industry_filtered_neg["Waste_%"],
    name='Waste'
)

trace5 = go.Bar(
    x=current_industry_filtered_neg.Country,
    y=current_industry_filtered_neg["LandUseandForestry_%"],
    name='Land Use and Forestry'
)

trace6 = go.Bar(
    x=current_industry_filtered_neg.Country,
    y=current_industry_filtered_neg["BunkerFuels_%"],
    name='Bunker Fuels'
)

trace7 = go.Bar(
    x=current_industry_filtered_neg.Country,
    y=current_industry_filtered_neg["ManufacturingConstruction_%"],
    name='Manufacturing/Construction'
)

trace8 = go.Bar(
    x=current_industry_filtered_neg.Country,
    y=current_industry_filtered_neg["Transportation_%"],
    name='Transportation'
)

data = [trace5, trace2, trace3, trace4, trace1, trace6, trace7,trace8]
layout = go.Layout(
    barmode='stack',
    legend=dict(orientation="h",y=-0.3),
    #title="Percentage of Green House Gas Contribution by Country (Negative Forestry Emission)"
    margin=dict(
        l=30,
        r=10,
        t=30,
        b=120
    )
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='GHG-neg')

## Individual Comparison (China)

In [19]:
china_sdg=SDG_linkages_graph_data[SDG_linkages_graph_data.index=="China"].iloc[:,10:]

In [20]:
china_sdg

,Energy_count_percent,Industrial_count_percent,Agriculture_count_percent,Waste_count_percent,LandForestry_count_percent,ManufacturingConstruction_count_percent,Transportation_count_percent,Other_count_percent,Other_count_overlap_percent
Country,,,,,,,,,
China,15.0,10.0,8.333333,1.666667,9.166667,11.666667,4.166667,41.666667,40.0

In [21]:
china_current=current_industry_filtered_neg[current_industry_filtered_neg.Country=="China"].iloc[:,15:]

In [22]:
china_current["bunker"]=china_current['BunkerFuels_%']

In [23]:
china_current.drop("BunkerFuels_%",inplace=True,axis=1)

In [30]:
china_current

,Energy_%,Industrial_%,Agriculture_%,Waste_%,LandUseandForestry_%,ManufacturingConstruction_%,Transportation_%,bunker
899,47.936052,11.908007,5.76846,1.625843,2.535847,23.492745,6.3694,0.363647

In [26]:
china_combined=pd.DataFrame((china_sdg.as_matrix()[0],china_current.as_matrix()[0]))

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:

Method .as_matrix will be removed in a future version. Use .values instead.

In [27]:
china_combined=china_combined.rename({0:"Current Emission" ,1:"INDC Commitments"},axis="index")

In [29]:
print(china_combined.iloc[1,:])

0    47.936052
1    11.908007
2     5.768460
3     1.625843
4     2.535847
5    23.492745
6     6.369400
7     0.363647
8          NaN
Name: INDC Commitments, dtype: float64

In [31]:

top_labels = ['Energy','Agriculture','Industrial<br>Process','Waste','Land and<br>Forestry','Manufacturing',"Transport","Others"]

colors = ['rgba(0,0,0,0.8)', 'rgba(38, 24, 74, 0.8)','rgb(102, 57, 131,0.8)', 'rgba(71, 58, 131, 0.8)',
          'rgba(122, 120, 168, 0.8)', 'rgba(164, 163, 204, 0.85)',
          'rgba(190, 192, 213, 1)','rgba(200,200,200, 1)']

x_data = [[48, 12, 5.8, 1.6, 2.5, 24, 6, 0.36],
          [15, 10, 8.3, 1.7, 9.2, 11.7, 4.2, 40],]

y_data = ['Current Greenhouse<br>Gas Emission ',
          'INDC Commitments']


traces = []

for i in range(0, len(x_data[0])):
    for xd, yd in zip(x_data, y_data):
        traces.append(go.Bar(
            x=[xd[i]],
            y=[yd],
            orientation='h',
            text = top_labels[i],
            hoverinfo = 'x+text',
            marker=dict(
                color=colors[i],
                line=dict(
                        color='rgb(248, 248, 249)',
                        width=1)
            )
        ))

layout = go.Layout(
    xaxis=dict(
        showgrid=False,
        showline=False,
        showticklabels=False,
        zeroline=False,
        domain=[0.15, 1]
    ),
    yaxis=dict(
        showgrid=False,
        showline=False,
        showticklabels=False,
        zeroline=False,
    ),
    barmode='stack',
    #paper_bgcolor='rgb(248, 248, 255)',
    #plot_bgcolor='rgb(248, 248, 255)',
    margin=dict(
        l=40,
        r=10,
        t=140,
        b=80
    ),
    showlegend=False,
    #title="China's Emission Contribution by Sector vs Future Commitments"
)

annotations = []

for yd, xd in zip(y_data, x_data):
    # labeling the y-axis
    annotations.append(dict(xref='paper', yref='y',
                            x=0.14, y=yd,
                            xanchor='right',
                            text=str(yd),
                            font=dict(family='Arial', size=10,
                                      color='rgb(67, 67, 67)'),
                            showarrow=False, align='right'))
    # labeling the first percentage of each bar (x_axis)
#     annotations.append(dict(xref='x', yref='y',
#                             x=xd[0] / 2, y=yd,
#                             text=str(xd[0]) + '%',
#                             font=dict(family='Arial', size=10,
#                                       color='rgb(248, 248, 255)'),
#                             showarrow=False))
    
    # labeling the first Likert scale (on the top)
#     if yd == y_data[-1]:
#         annotations.append(dict(xref='x', yref='paper',
#                                 x=xd[0] / 2, y=1.1,
#                                 text=top_labels[0],
#                                 font=dict(family='Arial', size=10,
#                                           color='rgb(67, 67, 67)'),
#                                 showarrow=False))
    space = xd[0]
    for i in range(1, len(xd)):
            # labeling the rest of percentages for each bar (x_axis)
#             annotations.append(dict(xref='x', yref='y',
#                                     x=space + (xd[i]/2), y=yd, 
#                                     text=str(xd[i]) + '%',
#                                     font=dict(family='Arial', size=10,
#                                               color='rgb(248, 248, 255)'),
#                                     showarrow=False))
            # labeling the Likert scale
#             if yd == y_data[-1]:
#                 annotations.append(dict(xref='x', yref='paper',
#                                         x=space + (xd[i]/2), y=1.1,
#                                         text=top_labels[i],
#                                         font=dict(family='Arial', size=10,
#                                                   color='rgb(67, 67, 67)'),
#                                         showarrow=False))
            space += xd[i]

layout['annotations'] = annotations

fig = go.Figure(data=traces, layout=layout)
py.iplot(fig, filename='China')

C:\Users\randy\Anaconda3\envs\py36\lib\site-packages\IPython\core\display.py:689: UserWarning:

Consider using IPython.display.IFrame instead

In [32]:

top_labels = ['Energy','Agriculture','Industrial<br>Process','Waste','Land and<br>Forestry','Manufacturing',"Transport","Others"]

colors = ['rgba(0,0,0,0.8)', 'rgba(38, 24, 74, 0.8)','rgb(102, 57, 131,0.8)', 'rgba(71, 58, 131, 0.8)',
          'rgba(122, 120, 168, 0.8)', 'rgba(164, 163, 204, 0.85)',
          'rgba(190, 192, 213, 1)','rgba(200,200,200, 1)']

x_data = [[48, 12, 5.8, 1.6, 2.5, 24, 6, 0.36],
          [15, 10, 8.3, 1.7, 9.2, 11.7, 4.2, 40],]

y_data = ['Current Greenhouse<br>Gas Emission ',
          'INDC Commitments']


traces = []

for i in range(0, len(x_data[0])):
    for xd, yd in zip(x_data, y_data):
        traces.append(go.Bar(
            x=[xd[i]],
            y=[yd],
            orientation='h',
            text = top_labels[i],
            hoverinfo = 'x+text',
            marker=dict(
                color=colors[i],
                line=dict(
                        color='rgb(248, 248, 249)',
                        width=1)
            )
        ))

layout = go.Layout(
    xaxis=dict(
        showgrid=False,
        showline=False,
        showticklabels=False,
        zeroline=False,
        domain=[0.15, 1]
    ),
    yaxis=dict(
        showgrid=False,
        showline=False,
        showticklabels=False,
        zeroline=False,
    ),
    barmode='stack',
    paper_bgcolor='rgb(248, 248, 255)',
    plot_bgcolor='rgb(248, 248, 255)',
    margin=dict(
        l=40,
        r=10,
        t=140,
        b=80
    ),
    showlegend=False,
    title="China's Emission Contribution by Sector vs Future Commitments"
)

annotations = []

for yd, xd in zip(y_data, x_data):
    # labeling the y-axis
    annotations.append(dict(xref='paper', yref='y',
                            x=0.14, y=yd,
                            xanchor='right',
                            text=str(yd),
                            font=dict(family='Arial', size=10,
                                      color='rgb(67, 67, 67)'),
                            showarrow=False, align='right'))
    # labeling the first percentage of each bar (x_axis)
#     annotations.append(dict(xref='x', yref='y',
#                             x=xd[0] / 2, y=yd,
#                             text=str(xd[0]) + '%',
#                             font=dict(family='Arial', size=10,
#                                       color='rgb(248, 248, 255)'),
#                             showarrow=False))
    
    # labeling the first Likert scale (on the top)
#     if yd == y_data[-1]:
#         annotations.append(dict(xref='x', yref='paper',
#                                 x=xd[0] / 2, y=1.1,
#                                 text=top_labels[0],
#                                 font=dict(family='Arial', size=10,
#                                           color='rgb(67, 67, 67)'),
#                                 showarrow=False))
    space = xd[0]
    for i in range(1, len(xd)):
            # labeling the rest of percentages for each bar (x_axis)
#             annotations.append(dict(xref='x', yref='y',
#                                     x=space + (xd[i]/2), y=yd, 
#                                     text=str(xd[i]) + '%',
#                                     font=dict(family='Arial', size=10,
#                                               color='rgb(248, 248, 255)'),
#                                     showarrow=False))
            # labeling the Likert scale
#             if yd == y_data[-1]:
#                 annotations.append(dict(xref='x', yref='paper',
#                                         x=space + (xd[i]/2), y=1.1,
#                                         text=top_labels[i],
#                                         font=dict(family='Arial', size=10,
#                                                   color='rgb(67, 67, 67)'),
#                                         showarrow=False))
            space += xd[i]

layout['annotations'] = annotations

fig = go.Figure(data=traces, layout=layout)
py.iplot(fig, filename='bar-colorscale')